# Generated by Django 3.2.25 on 2025-06-09 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_hora_creacion_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMu', models.CharField(max_length=200)),
                ('Desc', models.TextField()),
                ('FechSal', models.DateTimeField(blank=True, null=True)),
                ('Precio', models.TextField()),
                ('Muñeca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
