# Generated by Django 3.2.25 on 2025-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_monsterhigh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterhigh',
            name='Muñeca',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='monsterhigh',
            name='Precio',
            field=models.CharField(max_length=10),
        ),
    ]
