# Generated by Django 3.2.25 on 2025-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250609_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterhigh',
            name='Precio',
            field=models.CharField(max_length=150),
        ),
    ]
