# Generated by Django 3.2.25 on 2025-06-09 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_monsterhigh_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monsterhigh',
            old_name='Desc',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='monsterhigh',
            old_name='FechSal',
            new_name='Fecha_salida',
        ),
        migrations.RenameField(
            model_name='monsterhigh',
            old_name='NomMu',
            new_name='Nombre_modelo',
        ),
        migrations.RenameField(
            model_name='monsterhigh',
            old_name='Precio',
            new_name='Precio_actual',
        ),
        migrations.AddField(
            model_name='monsterhigh',
            name='Fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
